apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - host: us-west-2.highestpavedroadsinthealps.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80
