kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myadmin
subjects:
- kind: User
  name: root
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: myadmin
  apiGroup: rbac.authorization.k8s.io
