kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy
subjects:
- kind: User
  name: githubactions
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy
  apiGroup: rbac.authorization.k8s.io
