on:
  workflow_dispatch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Docker push and build demo

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: demo
          addLatest: true
          registry: 476728484325.dkr.ecr.us-west-2.amazonaws.com
          dockerfile: dockerfiles/demo/Dockerfile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
