on:
  workflow_dispatch:
  pull_request:
  push:

name: Docker ecr action demo

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

#https://github.com/NCAR/jupyterhub-deploy/actions/runs/247686198/workflow
      - name: Get SHA SHORT
        shell: bash
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

#https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions/64210623#64210623    
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "GITHUB_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "GITHUB_BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.aws_access_key_id }}
          secret_key: ${{ secrets.aws_secret_access_key }}
          registry: ${{ secrets.aws_ecr_registry }}
          cache_from: ${{ secrets.aws_ecr_registry }}/${{ secrets.aws_ecr_repo }}
          repo: ${{ secrets.aws_ecr_repo }}
          region: ${{ env.AWS_REGION }}
          tags: "latest,${{ env.GITHUB_BRANCH }}-${{ env.GITHUB_SHA_SHORT }}"
          daemon_off: false
          dockerfile: dockerfiles/demo/Dockerfile
